version: "2"

services:
  db:
    image: mongo:latest
    container_name: db
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db

  app:
    build: .
    container_name: app
    environment:
      NODE_ENV: production
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - db

volumes:
  db:
