export const STUDY_MAPS_POST = 'STUDY_MAPS_POST';
export const STUDY_MAPS_POST_SUCCESS = 'STUDY_MAPS_POST_SUCCESS';
export const STUDY_MAPS_POST_FAILURE = 'STUDY_MAPS_POST_FAILURE';

export const LINK_POST = 'LINK_POST';
export const LINK_POST_SUCCESS = 'LINK_POST_SUCCESS';
export const LINK_POST_FAILURE = 'LINK_POST_FAILURE';

export const BREADCRUMB_POST = 'BREADCRUMB_POST';
export const BREADCRUMB_POST_SUCCESS = 'BREADCRUMB_POST_SUCCESS';
export const BREADCRUMB_POST_FAILURE = 'BREADCRUMB_POST_FAILURE';

export const SEEN_UPDATE = 'SEEN_UPDATE';
export const SEEN_UPDATE_SUCCESS = 'SEEN_UPDATE_SUCCESS';
export const SEEN_UPDATE_FAILURE = 'SEEN_UPDATE_FAILURE';

export const BLINKSEEN_UPDATE = 'SEEN_UPDATE';
export const BLINKSEEN_UPDATE_SUCCESS = 'SEEN_UPDATE_SUCCESS';
export const BLINKSEEN_UPDATE_FAILURE = 'SEEN_UPDATE_FAILURE';

export const BREADCRUMB_LINK_POST = 'BREADCRUMB_LINK_POST';
export const BREADCRUMB_LINK_POST_SUCCESS = 'BREADCRUMB_LINK_POST_SUCCESS';
export const BREADCRUMB_LINK_POST_FAILURE = 'BREADCRUMB_LINK_POST_FAILURE';

export const MESSAGE_POST = 'MESSAGE_POST';
export const MESSAGE_POST_SUCCESS = 'MESSAGE_POST_SUCCESS';
export const MESSAGE_POST_FAILURE = 'MESSAGE_POST_FAILURE';

export const LINK_MESSAGE_POST = 'LINK_MESSAGE_POST';
export const LINK_MESSAGE_POST_SUCCESS = 'LINK_MESSAGE_POST_SUCCESS';
export const LINK_MESSAGE_POST_FAILURE = 'LINK_MESSAGE_POST_FAILURE';

export const SUBJECT_POST = 'SUBJECT_POST';
export const SUBJECT_POST_SUCCESS = 'SUBJECT_POST_SUCCESS';
export const SUBJECT_POST_FAILURE = 'SUBJECT_POST_FAILURE';

export const SET_STUDY_MAPS = 'SET_STUDY_MAPS';

export function setStudyMapsAction(study_maps) {
  return {
    type: SET_STUDY_MAPS,
    study_maps
  };
}
